### ISSUE TITLE
Compatibility with Supervisors

### ISSUE THREAD

**Issue by crqrdotcom** [simonewebdesign/elixir_pubsub#5]
Hello!

Thanks for the great work with this lib! I'm using this in a project and I start the PubSub in a Supervisor which requires the `start_link/1` (currently only `start_link/0` is available).

I'd like to suggest adding a list of options as the first argument to that function to make it compatible with the Supervisor and also allow to specify a name to the PubSub in case we want many of them.

Let me know what you think and if I can make a PR! Ty in advance.

**Comment by simonewebdesign** [comment]
I think when starting a Supervisor you can specify which `:start` function it should call when starting the child, so it can call `start_link/0` (or any custom function) instead of the default `start_link/1`.
But I guess makes sense to define a `start_link/1` as well, just for convenience.

As for specifying a name to the PubSub, I wonder what's your use case?

Anyway please go ahead with a PR! :)
